### PR TITLE
iOS 6 Compatibility

### PR DESCRIPTION
**Pull request by powerqian**
Fixed the display issue that the label's default white background will cover the whole red circle.
Changed the s.platform to 6.0 since it is working on iOS 6. In this way this library can be integrated to those project with 6.0 deployment target using CocoaPods.

### CODE REVIEW

**Comment by cwRichardKim** [comment]
Hey! thanks for you input, sorry for my late response.  The PR looks simple enough.  Do you mind describing the first issue (the white label thing) a little bit more?  A screenshot would be super helpful too.  Thanks!

**Comment by powerqian** [comment]
Hi,

In iOS 6, the default backgroundColor of a UILabel is white color. In the code, the frame of the countLabel is the same as redCircle, and on top of it. As a result, the redCircle is covered by a white background countLabel. Screenshot is as follows

photo-4

**Comment by cwRichardKim** [comment]
sweet.  Thanks!

**Comment by powerqian** [comment]
Please consider to publish an update to CocoaPods so that others can use this library for projects targeting iOS 6.

Thanks.

**Comment by cwRichardKim** [comment]
done! thanks again

**Pull request merged**
