### PR TITLE
Added option to place circle in any corner of the view

### PR DESCRIPTION
**Pull request by uncoverd**
Happy New Year! :tada: :sheep:

I was looking for this option but it wasn't implemented yet. This is my first pull request ever, and I am quite new to Objective-C so please don't hesitate to comment or guide me in the right direction.

### CODE REVIEW

**Comment by cwRichardKim** [comment]
Hey! This option already exists actually (if you check the readme, you'll see one image of the icon being on the left). I'm looking at your code and I don't think I agree with your design decision as it takes control away from the user. I think I know why you went for that (it reads more like english), but the current method (setCircleAtFrame:) allows the user pixel-perfect precision

**Comment by cwRichardKim** [comment]
I really appreciate the effort, but I don't think I can take your code, especially because it changes the interface, which means that when I update the code, everyone who is using has to change their code (it's not a cool thing to do)

**Comment by uncoverd** [comment]
I decided to implement this because I saw no easy way of placing the circle on a corner without having to fiddle with the exact pixel positions. I was just looking for a quick and cheap way to avoid the tedious corrections needed to make the circle look good on any corner (not just the default one) while prototyping my application's user interface. 
I also thought it would be good to offer an alternative to setting the exact pixel values, as the layout is displayed on all kinds of devices with different sizes and ratios on projects using AutoLayout. 
I can understand your point about backward compatibility. Thank you for your comments.

**Comment by uncoverd** [comment]
I removed all the changes that broke the interface in 59fda6d8baff0333217070f94b58719ed3bb082a. Maybe someone will find it useful :smiley:. Great job by the way, this repo made my life easier :+1:

**Comment by cwRichardKim** [comment]
yea thanks so much man, I didn't mean to come off so abruptly hahaha. I really appreciate your input!

**Pull request closed without merging**
