### PR TITLE
UIBarButtonItem item support

### PR DESCRIPTION
**Pull request by steilerDev**
Since the `UIBarButtonItem` (in opposite to `UITabBarItem`) does not have a badge count I am proposing this addition to your framework: A convenience initialiser for a `UIBarButtonItem`.

It is actually not a big deal but it took me several hours figuring out how to get the view without loosing build in functionality (like the ability to recognise taps). On top of that I am manipulating the size and position of the badge to fit the bar icon (Feel free to modify this if you don't like my values)

I was considering to change the font of the counter a little bit (because it is getting fairly small), but that would require some more changes.

Let me know what you think (especially since I am not really an Objective-C programmer, feel free to correct my style)

My second commit is adding a Navigation Controller to your example, so you can see what I did. When pressing the icon in the tab bar it should increment the counter animated.

### CODE REVIEW

**Comment by cwRichardKim** [comment]
sorry i turned off notifications for this by accident, I'm checking out the code now

**Comment by cwRichardKim** [comment]
looks good, thanks for the input!

**Comment by Shukuyen** [comment]
This doesn't work with UIBarButtonItems created with `-(instancetype)initWithImage:(UIImage *)image style:(UIBarButtonItemStyle)style target:(id)target action:(SEL)action` and `UIBarButtonItemStylePlain`. Any idea?

**Comment by cwRichardKim** [comment]
Are you using the cocoapod? I recently updated to add that feature, but haven't released a new version yet. Try cloning from master



—
(Choong-Won Richard Kim)

**Comment by Shukuyen** [comment]
I do, but specified that the pod should be taken from :head, because there was no tag for the latest commits yet. I can call `[[RKNotificationHub alloc] initWithBarButtonItem:menuButton];` but the badge doesn't show. The reason for that is that `[barButtonItem valueForKey:@"view"]` returns nil for my barButtonItem in `- (id)initWithBarButtonItem:(UIBarButtonItem *)barButtonItem`

**Comment by cwRichardKim** [comment]
@steilerDev thoughts?

**Comment by steilerDev** [comment]
puh...since the api that I am using is not documented (using kvc to get the view of the bar button should work in general) I really can't say why this is not working when initiating with an image.

I could try to give an educated guess: Since you are initialising the button using an image maybe there is no view accessible using the key "view" but rather something LIKE "imageView". I would need to investigate on all available values that are accessible when initiating the button with this initializer. Maybe I can find the time somewhere next week.

**Comment by Shukuyen** [comment]
Yes, the value for view is nil but there is a key "image" that contains the `UIImage`. 
I will try to work around that by initializing the `UIBarButtonItem` with custom view that contains the image.

**Comment by steilerDev** [comment]
Exactly what I though, we could adjust the notification hub initializer to check if the 'view' is available and if not try to get the 'image'. 
You should be able to attach the notification badge to the superview of the image. Let me know if that worked.

**Comment by Shukuyen** [comment]
It's working with a customView `UIBarButtonItem`, but now I run into the leftBarButtonItem positioning problem on iOS7+ ... can't use the negative spacer trick here, so I will need to find another way. Not a problem of RKNotificationHub or this pull request, though.

**Comment by cwRichardKim** [comment]
Thanks for the quick responses guys. Let me know if there is anything you need from me

**Pull request merged**
